#python 54

#for value in range(1, 21):
#	print(value)



#for value in range(1,1000001):
#	print(value)

#sumnumber = []

#for value in range(1,1000001):
	#sumnumber.append(value)

#print(min(sumnumber))

#print(max(sumnumber))
#
#print(sum(sumnumber))

odd_number = [value for value in range(1, 20, 2)]

for value in odd_number:
	print(value)


number_3 = [value for value in range(3, 31, 3)]

for value in number_3:
	print(value)


number_cube = [value * value * value for value in range(1, 11)]

for value in number_cube:
	print(value)